- hosts: application
  sudo: yes
  vars_files:
    - ../../../app/config/parameters.yml
  tasks:
    - name: Installs apache web server
      apt: pkg=apache2 state=installed update_cache=true
    - lineinfile: "dest=/etc/apache2/ports.conf regexp='^Listen 80' line='Listen 81' backrefs=yes"
      notify:
        - RestartApache
    - lineinfile: "dest=/etc/apache2/sites-available/000-default.conf regexp='^<VirtualHost \\*:80>' line='<VirtualHost *:81>' backrefs=yes"
      notify:
        - RestartApache
    - name: Install apache stuff
      apt: pkg="{{ item }}" state=installed update_cache=true
      with_items:
        - libapache2-mod-php5
      notify:
        - RestartApache
  handlers:
    - name: StartApache
      service: name=apache2 state=started
    - name: RestartApache
      service: name=apache2 state=restarted


